context
Graph1589/junior-course-boilerplate pull request #7
Opened 2021-11-14 14:47 UTC by Graph1589

2021-11-15 07:05 UTC, vislogurov requested changes

2021-11-15 07:05 UTC, vislogurov commented on src/components/SelectCategory/SelectCategory.jsx
> +                <p key={`${category}-category-btn`} className={styled.categoryButtonLabel}>
Отступов ради что-ли?)))

2021-11-15 07:05 UTC, vislogurov commented on src/App.jsx
> +    return _.uniq(categories);
Это уже давно можно сделать нативными средствами языка: через `[...new Set(myArray)]`. )))

2021-11-15 07:23 UTC, vislogurov commented on src/components/SelectCategory/SelectCategory.jsx
> +                  <button onClick={handleCategoryClick(category)} name={category} type="submit" className={categoryBtnCn}>
+ не хватает cursor: pointer, пользователю кажется, что по категориям нельзя кликнуть

2021-11-15 14:37 UTC, Graph1589 commented on src/App.jsx
> +    return _.uniq(categories);
Сначала сделал все на Set и что-то воткнулся на моменте где его нужно в Url представить, переделал на массив хД

2021-11-15 15:51 UTC, Graph1589 commented on src/components/SelectCategory/SelectCategory.jsx
> +                <p key={`${category}-category-btn`} className={styled.categoryButtonLabel}>
Это для капиталайза категории. Убрать?)

2021-11-18 12:34 UTC, vislogurov approved these changes

2021-11-19 10:32 UTC, merged